name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  FC: gfortran-12

on:
  push:
    paths:
    - "**.cmake"
    - "**/CMakeLists.txt"
    - "cmake/libraries.json"
    - ".github/workflows/ci.yml"
    - "!scripts/**"
    - "!cmake/package/**"

jobs:

  core:
    timeout-minutes: 40

    strategy:
      matrix:
        hwm14: [false]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v4

    - name: Install packages (Linux)
      if: runner.os == 'Linux'
      timeout-minutes: 10
      run: |
        sudo apt update
        sudo $(cmake -P scripts/requirements.cmake)

    - name: Install packages (MacOS)
      if: runner.os == 'macOS'
      timeout-minutes: 10
      run: $(cmake -P scripts/requirements.cmake)

    - name: Configure, build, install
      run: cmake -Dfind:BOOL=true -P build-online.cmake
