name: cmake_install

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
    - ".github/workflows/cmake_install.yml"
    - "scripts/install_cmake.cmake"

jobs:

  core:
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v3

    - name: install CMake
      run: cmake -P scripts/install_cmake.cmake
