name: cmake_install

on:
  push:
    paths:
    - ".github/workflows/cmake_install.yml"
    - "scripts/install_cmake.cmake"

jobs:

  new:
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: install CMake
      run: cmake -P scripts/install_cmake.cmake


# just says "error processing file". Bug with this Action?
  # old:
  #   timeout-minutes: 5

  #   runs-on: ubuntu-latest

  #   steps:

  #   - name: Setup cmake
  #     uses: jwlawson/actions-setup-cmake@v1
  #     with:
  #       cmake-version: '3.13.x'

  #   - name: install CMake
  #     run: cmake -P ${{ github.workspace }}/scripts/install_cmake.cmake
