name: ninja_install

on:
  push:
    paths:
    - ".github/workflows/ninja_install.yml"
    - "scripts/install_ninja.cmake"

jobs:

  core:
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v3

    - name: install Ninja
      run: cmake -P scripts/install_ninja.cmake
